### ISSUE TITLE
Failed to compile under pypy2-v6.0.0-linux64 

### ISSUE THREAD

**Issue by ddorian** [dgrunwald/rust-cpython#143]
Hi,

This module is installed by `https://github.com/snipsco/snips-nlu-utils`. On cpython it works fine, but on pypy I get a an error message of "Could not compile `cpython`". 

More details from verbose output here https://github.com/snipsco/snips-nlu-utils/issues/46#issuecomment-411389932

regards,
ddorian

**Comment by dgrunwald** [comment]
`python27-sys` is essentially all the Python C headers converted to Rust (including struct and macro definitions). Unless pypy is *binary* compatible with cpython, it won't work. I never looking at PyPy in detail but I was under the impression that it provides its own headers that are more-of-less source-compatible with `Python.h`, but result in a different ABI.
So what's likely needed here is that someone writes a `cpyext-sys` crate for linking Rust code against pypy; and then rust-cpython could use that instead of `python27-sys`.

**Comment by dgrunwald** [comment]
By the way, the particular problem in your log is even earlier: the python27-sys `build.rs` script fails determining whether your python interpreter has threading support; so `python27-sys` is compiled without threading support; but `rust-cpython` requires threading support.

**Comment by markbt** [comment]
PyPy is explicitly out of scope, we're focused on the CPython implementation.
