### ISSUE TITLE
How to pass byte-object to rust?

### ISSUE THREAD

**Issue by PureW** [dgrunwald/rust-cpython#145]
I'm exposing the following function to python:

```rust
// Rust
py_fn!(py, entry(json: Vec<u8>))
```

However, I'm seeing type-errors on the python side when calling this function:
```python
# python
entry(b"I am not json")
...
TypeError
```

How do I pass a bytes-object to Rust?

**Comment by PureW** [comment]
It worked if I send `list(b"I am not json")` instead.

**Comment by dgrunwald** [comment]
The problem here is that conversion to `Vec<T>` is handled by generic code that works the same for every `T`.
It works by calling `iter()` on the input object, and converting each element separately.
In Python 2, the elements of a byte string are themselves single-character-byte-strings, and those can't be converted to `u8`. A workaround is to instead use `bytearray(b'abc')`.
In Python 3, the elements of a byte string are normal integers, so the conversion to `Vec<u8>` is successful there.
Ideally, the conversion from byte strings to `Vec<u8>` would work directly (without the overhead of creating tons of python objects for the single character).
However, Rust hasn't stabilized specialization yet, so this conversion is only available if you use `--features nightly`.

To be precise: with `--features nightly`, the conversion to `Vec<T>` for primitive T first tries the buffer protocol, and only falls back to the sequence protocol if that fails.
Without nightly/specialization, it always uses the sequence protocol.

**Comment by dgrunwald** [comment]
I just added an impl that allows using `py_fn!(py, entry(json: &[u8]))`.
We don't have a generic impl for `&[T]` (at least so far), so this one works even on stable.
As a bonus, this way the slice can point into the existing `bytes` object (since that's also immutable on the Python side), completely avoiding any copy of the data.
Other types like `bytearray` still are copied, so that Python can't modify them while the `&[u8]` exists. You could use `PyBuffer` to access those without any copies, but then the access code needs to deal with `&[Cell<u8>]` due to the possible mutability.

**Comment by PureW** [comment]
I'll close this issue as the added `impl` above by @dgrunwald solved my particular issue. Feel free to re-open if you'd prefer this to stay open.
