### ISSUE TITLE
run_python_script_try_interpreter and virtualenv

### ISSUE THREAD

**Issue by novocaine** [dgrunwald/rust-cpython#16]
In https://github.com/dgrunwald/rust-cpython/commit/2904330b1c316ead178f020f845db0ca0fbbaf2e, run_python_script_try_interpreter now tries to locate more version specifically named python interpreters to help it locate the correct interpreter.

The problem with this is that although it helps locate say 'python3' on many popular linux distros and os x, it doesn't work correctly with virtualenv, which only adds a link for 'python', not pythonX or pythonX.X.

So for example:

```
jsalter@sydxplanssh ~ $ which python
/usr/bin/python
jsalter@sydxplanssh ~ $ virtualenv testenv
jsalter@sydxplanssh ~ $ source testenv/bin/activate
(testenv)jsalter@sydxplanssh ~ $ which python
/home/jsalter/testenv/bin/python
(testenv)jsalter@sydxplanssh ~ $ which python2.7
/usr/bin/python2.7
```

virtualenv sets an environment variable VIRTUAL_ENV - maybe we could check if that is present and if it is, just run 'python'?

**Comment by dgrunwald** [comment]
Yes, that's a good idea. I was trying to fix the problem of compiling python3-sys on a standard debian system, which was failing due to it trying to use python 2.7.

Crazy idea: Maybe we should combine python27-sys and python3-sys into a single crate where `build.rs` invokes `python` to see which code base to build? That would also remove the need for `cargo --no-default-features` when targeting a different python than the default.

Then also disable pkg-config by default -- it's was quite annoying on travis to have pkg-config select the system python 3.2 when I wanted python 3.3/3.4. That would make virtualenv sufficient to pick the python version.

**Comment by dgrunwald** [comment]
I changed the interpreter-finding logic to try "python" first, and only fall back to the other options if the interpreter version doesn't match the expected version.

(by the way, on my debian system, virtualenv was also creating a `python3` binary)
