### ISSUE TITLE
build with bazel

### ISSUE THREAD

**Issue by ali5h** [dgrunwald/rust-cpython#233]
I am trying to use `rust-cpython` with bazel, for that i am trying to skip running `build.rs` and pass all the needed `cfg` to `rustc` directly. you can find the example here https://github.com/ali5h/bazel_rust_python.

So far I have these configured for both `rust-cpython` and `python3-sys`.
```
additional_flags = [
 "--cfg=py_sys_config=\\\"WITH_THREAD\\\"",
 "--cfg=Py_3_4",
 "--cfg=Py_3_5",
 "--cfg=Py_3_6",
 "--cfg=Py_3_7",
]
```
The flags are passed to rustc. 

But I am getting this error

```
error: expected type, found `$`
  --> rust_cpython_test/src/lib.rs:5:1
   |
5  | / py_module_initializer!(rust2py, |py, m| {
6  | |     m.add(py, "__doc__", "This module is implemented in Rust.")?;
7  | |     m.add(
8  | |         py,
...  |
12 | |     Ok(())
13 | | });
   | |___^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Any help is appreciated.

**Comment by markbt** [comment]
Does `-Z macro-backtrace` with a nightly compiler give any useful output?  I tried to repro this, but I was able to compile that module just fine.

**Comment by ali5h** [comment]
run `bazel build //rust_cpython_test/...`
thank for looking at this

**Comment by markbt** [comment]
I tracked the failure down to rust-cpython's use of the paste crate.   I've extracted the problem into a minimal repro that doesn't use cpython.  See https://gist.github.com/markbt/f748421d7c12effa8c5066791ce72d69 for the patch.  Run `bazel build //paste_test:use` and you should get the same error.

In particular, the error seems to be caused by a `$crate` inside a `paste::item! { }` invocation.  It doesn't happen with Cargo builds, so I assume there must be something weird about how Bazel is building the paste crate.

I see that you're currently using paste 0.1.16.  It looks like paste 0.1.17 just got released, which includes some changes to the parsing, so maybe that will work.

**Comment by ali5h** [comment]
great, paste 0.1.17 fixed the issue, thanks a lot
