### ISSUE TITLE
cargo build requires python3-sys 0.1.2

### ISSUE THREAD

**Issue by iduartgomez** [dgrunwald/rust-cpython#34]
hi there, on the travis build you used your local copy of python3-sys so it passed the build, but when you fetch the crate with cargo it downloads python3-sys 0.1.1 and it doesn't build properly.

i had to download the crate and use a local copy to make it work (with current nightly build as of 11/11/2015) as well as that one that passed the build (07/11/2015). you may want to update the python3-sys / python27 crates on crate.io

may as well ask if you have any plans for stabilization (what's stopping it, I guess the stabilization of the libc library itself?)

p.s: i guess is the same for python 2.7 version, haven't tried though

**Comment by dgrunwald** [comment]
For python(27|3)-sys, the latest version on crates.io should work with stable rust.

For rust-cpython itself, I've given up on releasing a new version on crates.io. Given that you'll need to use a recent version anyways due to changes in nightly rust, you might as well use a git dependencies.
I've recently updated the readme in that direction; but it looks like cargo is still downloading python*-sys from crates.io :(

python*-sys should be pretty stable, except for changes to the c_* type aliases in libc. However it's not complete yet (grep for "TODO"), so I don't think it deserves a 1.0 label yet.

rust-cpython itself is highly unstable: I'm still experimenting with the API: #15 isn't completely implemented yet; and the story around `PyRustType` is unclear.
It also depends on unstable rust features, most critically [interpolate_idents](https://github.com/SkylerLipthay/interpolate_idents) for working around rust-lang/rust#12249; and `#![feature(unsafe_no_drop_flag)]` so that `PyObject` has the same memory layout as `*mut ffi::PyObject` (important for `PyTuple::as_slice()` and some other methods).
