### ISSUE TITLE
This is how I'm accessing Py_buffer objects [question]

### ISSUE THREAD

**Issue by royalstream** [dgrunwald/rust-cpython#51]
This is how I'm accessing `Py_buffer` objects.
It's definitely working but I feel uncomfortable using the `_detail` module because the code clearly says it should **not** be used directly.

``` rust
fn get_pybuffer(po:&PyObject) -> Option<_detail::ffi::Py_buffer>
{
    let ptr = po.as_ptr();
    unsafe {
        let mut buff: _detail::ffi::Py_buffer = mem::zeroed();
        match (*(*(*ptr).ob_type).tp_as_buffer).bf_getbuffer {
            Some(buffproc) => {
                buffproc(ptr, &mut buff as *mut _detail::ffi::Py_buffer, _detail::ffi::PyBUF_STRIDES | _detail::ffi::PyBUF_FORMAT | _detail::ffi::PyBUF_WRITABLE);
                Some(buff)
            },
            None => None
        }
    }
}
```

My plan is to create something similar to the `buffer_info` object from [pybind11](https://github.com/pybind/pybind11) but if there's a better way please let me know. I'm also wondering if I should just call `PyObject_GetBuffer` directly as opposed to all that `.ob_type.tp_as_buffer.bf_getbuffer`

PS: I'm relatively new to rust so, please bear with me if I'm missing something obvious.

**Comment by dgrunwald** [comment]
You directly import the `python27-sys` or `python3-sys` crate instead of using the hidden export in `_detail`.
Though if you are compiling your code for both Python 2 and Python 3, I'll grant you that using a re-export is simpler than picking the right crate to import. I might consider adding an "official" re-export outside of `_detail`.

Eventually I think rust-cpython should provide a safe abstraction over python buffers, but that's not a priority at the moment.
