### ISSUE TITLE
PYTHON_SYS_EXECUTABLE not work on windows with quotes

### ISSUE THREAD

**Issue by Dushistov** [dgrunwald/rust-cpython#97]
I have python in path `c:\python36\python.exe`,
if I run run bulid in such way:

```
set PYTHON_SYS_EXECUTABLE="c:\python36\python.exe"
cargo build
```

with error like `os can not find file`,
but if I remove quotes all works fine:

```
set PYTHON_SYS_EXECUTABLE=c:\python36\python.exe
cargo build
```

but what about spaces in file path, if I have python36 somewhere `c:\program files\python36` what should I do?

**Comment by ssokolow** [comment]
According to [this StackOverflow answer](http://stackoverflow.com/a/8582277/435253), the Windows quoting parser requires you to do this:

    set "PYTHON_SYS_EXECUTABLE=c:\python36\python.exe"

**Comment by Dushistov** [comment]
>According to this StackOverflow answer, the Windows quoting parser requires you to do this:

thanks, looks like cmd.exe quotes handle much more complex then in `/bin/sh`

**Comment by ssokolow** [comment]
> thanks, looks like cmd.exe quotes handle much more complex then in /bin/sh

Not really. Judging by the other answers, it's just that the default behaviour is to ignore quotes within arguments (ie. `foo"bar"` would be passed through literally) and, if it can't find a partner for the quote, it'll treat it literally rather than complaining or displaying a multi-line input prompt.

Apparently `SETLOCAL enabledelayedexpansion` will get you more `/bin/sh`-like quoting behaviour. (ie. `foo"bar"` becomes `foobar`, but `foo="bar baz"` becomes `foo=bar baz` too.)

...sort of like how Unixy shells have things like `shopt extglob` to enable extended pattern matching.
